# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0005_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile-pic/kakashi.jpg', upload_to='profile-pic/'),
        ),
    ]
